spring.application.name=vinylshop

spring.datasource.url=jdbc:mysql://localhost:3306/vinylshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=lucky2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=9f2b4c1e7a8d3f6b0c5e1a9d2f7b8c4e6a1d3f9c7b5e2a8d4f6c1b9e3a7d5f8c2e4b6a9d1f3c7b5e8a2d4c6f9b1a3e7
jwt.expiration=86400000